name: Pre-Production-Cron
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: # Enables manual trigger
jobs:
  production:
    name: Pre-Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -r
      - name: Run
        run: cargo run
        env:
          GSTALDERCONFIG: ${{ secrets.GSTALDERCONFIG_TEST }}
